# Generated by Django 4.2.7 on 2023-12-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fireballsnn_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonFormattedCourtName',
            fields=[
                ('value', models.CharField(default='', max_length=200)),
                ('formatted', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fireballsnn_api.courtname')),
            ],
        ),
        migrations.RemoveField(
            model_name='courtname',
            name='case',
        ),
    ]
