# Generated by Django 5.0 on 2023-12-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireballsnn_api', '0002_nonformattedcourtname_remove_courtname_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtname',
            name='case',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nonformattedcourtname',
            name='case',
            field=models.CharField(default='', max_length=20),
        ),
    ]
